// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package logisticq

import (
	"database/sql"
	"time"
)

type Assignment struct {
	ID                     int64
	ShipmentID             int64
	ApplicationExternalID  int64
	PickupPointExternalID  sql.NullInt64
	DropoffPointExternalID sql.NullInt64
	WeightKg               float64
	VolumeM3               float64
	CreatedAt              time.Time
}

type LogisticPoint struct {
	ID        int64
	Title     string
	Address   string
	Lat       sql.NullFloat64
	Lon       sql.NullFloat64
	CreatedAt time.Time
}

type RoutePoint struct {
	ID              int64
	ShipmentID      int64
	PointID         int64
	PlannedArriveAt time.Time
	Ordinal         int16
}

type Shipment struct {
	ID          int64
	MaxWeightKg float64
	MaxVolumeM3 float64
	DepartureAt time.Time
	Status      string
	CreatedAt   time.Time
}
