// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route_points.sql

package logisticq

import (
	"context"
	"time"
)

const insertRoutePoint = `-- name: InsertRoutePoint :exec
INSERT INTO route_points (shipment_id,point_id,planned_arrive_at,ordinal)
VALUES ($1,$2,$3,$4)
`

type InsertRoutePointParams struct {
	ShipmentID      int64
	PointID         int64
	PlannedArriveAt time.Time
	Ordinal         int16
}

func (q *Queries) InsertRoutePoint(ctx context.Context, arg InsertRoutePointParams) error {
	_, err := q.db.ExecContext(ctx, insertRoutePoint,
		arg.ShipmentID,
		arg.PointID,
		arg.PlannedArriveAt,
		arg.Ordinal,
	)
	return err
}
