// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cargo.sql

package officeq

import (
	"context"
	"database/sql"
)

const insertCargo = `-- name: InsertCargo :one
INSERT INTO cargos (name, boxes, total_weight, total_volume, special_requirements)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type InsertCargoParams struct {
	Name                string
	Boxes               int64
	TotalWeight         float64
	TotalVolume         float64
	SpecialRequirements sql.NullString
}

func (q *Queries) InsertCargo(ctx context.Context, arg InsertCargoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertCargo,
		arg.Name,
		arg.Boxes,
		arg.TotalWeight,
		arg.TotalVolume,
		arg.SpecialRequirements,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
