// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package officeq

import (
	"database/sql"
	"time"
)

type Application struct {
	ID             int64
	PickupPointID  int64
	DropoffPointID int64
	ClientID       int64
	CargoID        int64
	RecipientID    int64
	Status         string
	CreatedAt      time.Time
	AcceptedAt     sql.NullTime
	DispatchedAt   sql.NullTime
	DeliveredAt    sql.NullTime
}

type Cargo struct {
	ID                  int64
	Name                string
	Boxes               int64
	TotalWeight         float64
	TotalVolume         float64
	SpecialRequirements sql.NullString
}

type Client struct {
	ID    int64
	Name  string
	Inn   string
	Fio   string
	Tel   string
	Email string
}

type Recipient struct {
	ID          int64
	NameCompany string
	Address     string
	Fio         string
	Telephone   string
}
