// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipients.sql

package officeq

import (
	"context"
)

const insertRecipient = `-- name: InsertRecipient :one
INSERT INTO recipients (name_company, address, fio, telephone)
VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertRecipientParams struct {
	NameCompany string
	Address     string
	Fio         string
	Telephone   string
}

func (q *Queries) InsertRecipient(ctx context.Context, arg InsertRecipientParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRecipient,
		arg.NameCompany,
		arg.Address,
		arg.Fio,
		arg.Telephone,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
